### ISSUE TITLE
Document CI configuration and provide current status

### ISSUE THREAD

**Issue by abailly** [cardano-foundation/cardano-wallet-agda#118]
My local build of [current main](https://github.com/cardano-foundation/cardano-wallet-agda/tree/f3479b501a2efe50bcf1ee0d09bc2d1325a982e7)failed to compile, giving the following error:

```
[42 of 71] Compiling Cardano.Wallet.Read.Chain ( haskell/Cardano/Wallet/Read/Chain.hs, /Users/arnaud/projects/cardano-wallet-agda/dist-newstyle/build/aarch64-osx/ghc-9.10.1/cardano-wallet-read-0.2024.8.27/build/Cardano/Wallet/Read/Chain.o, /Users/arnaud/projects/cardano-wallet-agda/dist-newstyle/build/aarch64-osx/ghc-9.10.1/cardano-wallet-read-0.2024.8.27/build/Cardano/Wallet/Read/Chain.dyn_o )
haskell/Cardano/Wallet/Read/Chain.hs:22:7: error: [GHC-97219]
    Duplicate record field ‘headerHash’ in export list:
       ‘ChainTip(..)’ exports the field ‘headerHash’
       belonging to the constructor ‘BlockTip’
         imported from ‘Cardano.Wallet.Read.Chain.Point’ at haskell/Cardano/Wallet/Read/Chain.hs:54:7-19
         (and originally defined
            at haskell/Cardano/Wallet/Read/Chain/Point.hs:117:11-20)
       ‘ChainPoint(..)’ exports the field ‘headerHash’
       belonging to the constructor ‘BlockPoint’
         imported from ‘Cardano.Wallet.Read.Chain.Point’ at haskell/Cardano/Wallet/Read/Chain.hs:53:7-21
         (and originally defined
            at haskell/Cardano/Wallet/Read/Chain/Point.hs:77:11-20)
    Suggested fix: Perhaps you intended to use DuplicateRecordFields
   |
22 |     , ChainTip (..)
   |       ^^^^^^^^^^^^^

haskell/Cardano/Wallet/Read/Chain.hs:22:7: error: [GHC-97219]
    Duplicate record field ‘slotNo’ in export list:
       ‘ChainTip(..)’ exports the field ‘slotNo’
       belonging to the constructor ‘BlockTip’
         imported from ‘Cardano.Wallet.Read.Chain.Point’ at haskell/Cardano/Wallet/Read/Chain.hs:54:7-19
         (and originally defined
            at haskell/Cardano/Wallet/Read/Chain/Point.hs:116:11-16)
       ‘ChainPoint(..)’ exports the field ‘slotNo’
       belonging to the constructor ‘BlockPoint’
         imported from ‘Cardano.Wallet.Read.Chain.Point’ at haskell/Cardano/Wallet/Read/Chain.hs:53:7-21
         (and originally defined
            at haskell/Cardano/Wallet/Read/Chain/Point.hs:76:11-16)
    Suggested fix: Perhaps you intended to use DuplicateRecordFields
   |
22 |     , ChainTip (..)
   |       ^^^^^^^^^^^^^

```

In retrospect it seems obvious this is caused by a discrepancy in GHC versions (I am not using nix) as the existing [CI pipeline](https://buildkite.com/cardano-foundation/cardano-wallet-agda/builds/389) is green. However I overlooked this information as the only indication of CI results is in the commit line, and not at the top of the README page as is customary in a lot of OSS projects. 

I think it would be good to have a link in the `README.md`, e.g. like traditional badges, and perhaps also document how CI is done in the project. 

**Note 1**: an additional issue is that CI is not accessible to people outside of CF organisation, perhaps we should consider a different option?

**Note 2**: perhaps we want to make the use of nix mandatory to build this project?

**Comment by HeinrichApfelmus** [comment]
We do have a CI build pipeline that does all three things that you mention:

https://github.com/cardano-foundation/cardano-wallet-agda/blob/main/.buildkite/pipeline.yml

and this pipeline passes on `main`.

It looks like something more nuanced going on.

**Comment by abailly** [comment]
There's no indication of a CI in the `README.md`, like a badge. I looked at the `Actions` tab and could not find anything hence why I thought there was no CI in place.
I have rewritten the issue accordingly.

**Comment by HeinrichApfelmus** [comment]
> There's no indication of a CI in the README.md, like a badge. I looked at the Actions tab and could not find anything hence why I thought there was no CI in place.

It's not a highly visible indicator, but Github does add a small green checkmark next to the commit hash when CI runs successfully.

My recommendation is to phrase things like this in the form of a question, e.g. "Which version of GHC did you test the library with?" that will highlight a problem when CI is missing, but also avoid making a false claim in the event that CI is not missing.

**Comment by abailly** [comment]
My apologies if my proposal came across as rude or inappropriate. And thank you for the recommendation.

I still think it would be helpful to developers unfamiliar with the repository to provide a more obvious CI status badge and link to the build. This would more easily avoid the kind of misunderstanding we are having here as wannabe contributors could more easily find the information they need to understand why their build is failing locally.

Of course, we could also imagine to make the use of nix mandatory: it's already listed as a prerequisite after all.
